# You will need to change this to point at your own repository
backend:
  name: github
  repo: zefman/gridsome-netlifycms-relations

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "id"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name"]
        displayFields: ["name"]
        valueField: "name"

  - name: "authors" 
    label: "Authors" 
    folder: "content/authors"
    create: true
    slug: "{{slug}}"
    identifier_field: "name"
    fields:
      - {label: "ID", name: "id", widget: "id"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Profile", name: "profile", widget: "markdown"}